package conoha.model;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.pk
     *
     * @mbggenerated
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.small
     *
     * @mbggenerated
     */
    private String small;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.large
     *
     * @mbggenerated
     */
    private String large;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    public Img(Integer pk, String small, String large, String id) {
        this.pk = pk;
        this.small = small;
        this.large = large;
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    public Img() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.pk
     *
     * @return the value of img.pk
     *
     * @mbggenerated
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.pk
     *
     * @param pk the value for img.pk
     *
     * @mbggenerated
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.small
     *
     * @return the value of img.small
     *
     * @mbggenerated
     */
    public String getSmall() {
        return small;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.small
     *
     * @param small the value for img.small
     *
     * @mbggenerated
     */
    public void setSmall(String small) {
        this.small = small == null ? null : small.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.large
     *
     * @return the value of img.large
     *
     * @mbggenerated
     */
    public String getLarge() {
        return large;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.large
     *
     * @param large the value for img.large
     *
     * @mbggenerated
     */
    public void setLarge(String large) {
        this.large = large == null ? null : large.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.id
     *
     * @return the value of img.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.id
     *
     * @param id the value for img.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}