package conoha.dao;

import conoha.model.Calendar;
import conoha.model.CalendarExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface CalendarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    @Delete({
        "delete from calendar",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    @Insert({
        "insert into calendar (id, cid, ",
        "title, start, ",
        "end, notes, ad, ",
        "location, url)",
        "values (#{id,jdbcType=INTEGER}, #{cid,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{start,jdbcType=TIMESTAMP}, ",
        "#{end,jdbcType=TIMESTAMP}, #{notes,jdbcType=VARCHAR}, #{ad,jdbcType=BIT}, ",
        "#{location,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR})"
    })
    int insert(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int insertSelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    List<Calendar> selectByExample(CalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, cid, title, start, end, notes, ad, location, url",
        "from calendar",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Calendar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Calendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    @Update({
        "update calendar",
        "set cid = #{cid,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "start = #{start,jdbcType=TIMESTAMP},",
          "end = #{end,jdbcType=TIMESTAMP},",
          "notes = #{notes,jdbcType=VARCHAR},",
          "ad = #{ad,jdbcType=BIT},",
          "location = #{location,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Calendar record);
    @Select({
            "select",
            "id, cid, title, start, end, notes, ad, location, url",
            "from calendar"
    })
    List<Calendar> selectAll();
}