package conoha.dao;

import conoha.model.Img;
import conoha.model.ImgExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    @Delete({
        "delete from img",
        "where pk = #{pk,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    @Insert({
        "insert into img (pk, small, ",
        "large, id)",
        "values (#{pk,jdbcType=INTEGER}, #{small,jdbcType=VARCHAR}, ",
        "#{large,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR})"
    })
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    int insertSelective(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    List<Img> selectByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "pk, small, large, id",
        "from img",
        "where pk = #{pk,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Img selectByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated
     */
    @Update({
        "update img",
        "set small = #{small,jdbcType=VARCHAR},",
          "large = #{large,jdbcType=VARCHAR},",
          "id = #{id,jdbcType=VARCHAR}",
        "where pk = #{pk,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Img record);

    @Select({
            "select",
            "pk, small, large, id",
            "from img"
    })
    List<Img> getAll();
}